server.port=8000

spring.application.name=inventory
spring.datasource.url=jdbc:postgresql://localhost:5432/ebs
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.name=ebs
spring.jpa.hibernate.ddl-auto=update

