spring.application.name=booking
server.port=8001

spring.datasource.url=jdbc:postgresql://localhost:5432/ebs
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.name=ebs
spring.jpa.hibernate.ddl-auto=update

inventory.service.url=http://localhost:8000
